server.contextPath: "/springboothelloworld"
logging.level.root: INFO
logging.level.com.mikerott.springboothelloworld: DEBUG

spring.jackson.serialization.WRITE_NULL_MAP_VALUES: false
spring.jackson.default-property-inclusion: non_empty

# if someone sends a HUGE cookie header, we might hit the Tomcat 8192 byte limit
# see also: https://maxchadwick.xyz/blog/http-response-header-size-limits
server.max-http-header-size: 16384
