# For common properties, see: https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
server:
  servlet:
    contextPath: "/tlsdetector"

spring.jackson.serialization.WRITE_NULL_MAP_VALUES: false
spring.jackson.default-property-inclusion: non_empty

# if someone sends a HUGE cookie header, we might hit the Tomcat 8192 byte limit
# see also: https://maxchadwick.xyz/blog/http-response-header-size-limits
server.max-http-header-size: 16384

logging:
  level:
    root: INFO
    com.mikerott.tlsdetector: DEBUG
    # org.apache.http.wire: DEBUG
